name: MysteryCrate
main: JackMD\MysteryCrate\Main
api: [3.0.0-ALPHA11, 3.0.0-ALPHA12]
version: 3.0.0
authors: [JackMD]
load: POSTWORLD
description: This plugins adds MysteryCrates with op items.
website: https://github.com/JackMD/MysteryCrate

permissions:
 mc.command.key:
  default: op
  description: "Allows use of /key command"
 mc.command.xyz:
  default: op
  descrption: "Allows use of /xyz command"
